### ISSUE TITLE
Unable to delete a book

### ISSUE THREAD

**Issue by knjk04** [Project-Books/book-project#501] opened 2020-10-24 17:37 UTC
**Describe the bug**

Unable to delete an existing book.

**To Reproduce**
Steps to reproduce the behaviour:
1. Log in
2. Go to 'My books'
3. Select 'All shelves' from the dropdown list
4. Select a book
5. Click on 'delete'
6. See error

**Expected behaviour**

The book is deleted.

**Additional context**

[Stack trace](https://gist.github.com/knjk04/c0a6a9f7d8bf6fa2d2a61682059d6869)

**Comment by PirtiXcode** [comment] 2020-10-24 23:52
Hey I want to contribute on this issue

**Comment by knjk04** [comment] 2020-10-25 06:13
Thanks for taking an interest in this issue!

As this is a high-priority issue, we're looking to have this completed as soon as possible -- ideally within a week after being assigned.

Are you fine with this? If so, I can assign you to the issue

**Comment by PirtiXcode** [comment] 2020-10-26 12:13
Okay,I'll look into as soon as possible

**Comment by knjk04** [comment] 2020-11-06 06:20
@PirtiXcode How are you getting on with this issue? If you need any help on this, feel free to reach out to us on [Slack](https://join.slack.com/t/teambookproject/shared_invite/zt-i7lept44-rgJ9yB0A2vedJTLyyfkjKQ)

If you need more time, that's fine, but please let us know.

**Comment by knjk04** [comment] 2020-11-14 07:06
@PirtiXcode Unfortunately, as we have not heard back from you in a while, I will unassign you from the issue. This is in line with our contributing guidelines.

**Comment by jcrosswh** [comment] 2020-11-25 20:03
Hello @knjk04, I'd like to help with this issue.

The main issue that is causing this error is that the `customShelf` field in the `Book` class contains the cascade type `CascadeType.MERGE` in its list, and when the delete is performed, that field is triggering the insert call into the custom_shelf table.  Since the book has null for the custom_shelf field, and the form is updated to use the user's inserted custom shelf (set to default as "ShelfName"), since the bean has no knowledge of the link between the two, it assumes that the data needs to be inserted, hence the call.  Since the DB has the unique index already present that's where the error occurs.

One side note, in order to reproduce this error right now, I had to comment out the call to `clearErrors` from the `BookForm.openForm` method.  If that call remains, then you now get a new error about violating a not null constraint on `BookService.delete`.  I do see why that method call was first put in; opening a new book form immediately runs the validations and shows errors if it's not there.

Solving this I see may be tricky.  The first question I would ask is do you really need the merge on cascade operations for the custom shelf?  If not, the quick fix for this issue would be to remove that statement.  If it is, then this may go into a data design discussion on how to solve it.  The second question I would ask, is the custom shelf designed to be optional or not?  I see on the add book form that the field is starred, but it doesn't start as red indicating that it's required.  If I try to add a new book but leave the custom shelf as null, I get a SQL error about the shelf name not allowed to be null.

**Comment by knjk04** [comment] 2020-11-28 08:25
Welcome back @jcrosswh! Apologies for the delay in getting back to you. 

> do you really need the merge on cascade operations for the custom shelf?

I could be wrong about this, but I don't think it's needed. 

> The second question I would ask, is the custom shelf designed to be optional or not?

It should be optional, but the fact that it's currently not is a bug (see #245).

Thanks a lot for looking into this!

**Closed** 2020-12-09 08:37 UTC
Labels: bug, hibernate, high-priority, impact: high
